version: 2.1

orbs:
  docker: circleci/docker@2.1.2
jobs:
  build:
    executor:
        name: docker/docker
        tag: "3.6"
    steps:
      - checkout
      - docker/install-docker-tools
      # Install Docker client
      - setup_remote_docker:
            docker_layer_caching: true
      # Install Azure CLI
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      # Login to Azure
      - run:
          name: Login to Azure
          command: |
                az login \
                --service-principal \
                --user "1ae5290a-5365-436b-bc37-3bfb556cccb3" \
                --tenant "15aeef68-4238-42b3-bf77-9d4ffe8b7c5f" \
                --federated-token "${CIRCLE_OIDC_TOKEN}" 
       # Login to Azure Container Registry
      - run:
          name: Login to Azure Container Registry
          command: |
            az acr login -n containerregistrytest1 --expose-token
      - run:
          name: Show current working directory
          command: echo $CIRCLE_WORKING_DIRECTORY
      # Build Docker images
      - run:
          name: Build Docker Images
          command: |
            cd ~/project/AspNetDistributedCaching
            ls
            docker login containerregistrytest1.azurecr.io -u containerregistrytest1 -p HtICsNVIIp3n3auKICInfRM/q2+J89Ez8rc09vnLz/+ACRC+F2Rh 
            cd ~/project/AspNetDistributedCaching 
            echo $CIRCLE_WORKING_DIRECTORY
            ls
            docker-compose up -d 

      # Push Docker images to Azure Container Registry
      - run:
          name: Push Docker Images to ACR
          command: |
            docker login containerregistrytest1.azurecr.io -u containerregistrytest1 -p HtICsNVIIp3n3auKICInfRM/q2+J89Ez8rc09vnLz/+ACRC+F2Rh 
            cd ~/project/AspNetDistributedCaching 
            docker images
            docker ps
            docker tag rediscommander/redis-commander:latest containerregistrytest1.azurecr.io/rediscommander/redis-commander:latest
            docker tag mongo:latest containerregistrytest1.azurecr.io/mongo:latest
            docker tag mongo-express:latest containerregistrytest1.azurecr.io/mongo-express:latest
            docker tag redis:6-alpine containerregistrytest1.azurecr.io/redis:6-alpine
            docker push containerregistrytest1.azurecr.io/rediscommander/redis-commander:latest
            docker push containerregistrytest1.azurecr.io/mongo:latest
            docker push containerregistrytest1.azurecr.io/mongo-express:latest
            docker push containerregistrytest1.azurecr.io/redis:6-alpine 

workflows:
  version: 2
  build:
    jobs:
      - build