version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Install Docker client
      - run:
          name: Install Docker client
          command: |
            sudo apt update
            sudo apt install -y docker.io

      # Install Azure CLI
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      # Login to Azure Container Registry
      - run:
          name: Azure Container Registry Login
          command: echo "$AZURE_CONTAINER_REGISTRY_PASSWORD" | az login --username sieusaongaytho@gmail.com --password phung60201982
          az acr login -n containeregistrytest --expose-token


      # Build Docker images
      - run:
          name: Build Docker Images
          command: |
            docker-compose build

      # Push Docker images to Azure Container Registry
      - run:
          name: Push Docker Images to ACR
          command: |
            docker-compose push

workflows:
  version: 2
  build:
    jobs:
      - build