version: 2.1

orbs:
  docker: circleci/docker@2.1.2
jobs:
  build:
    executor:
        name: docker/docker
        tag: "3.6"
    steps:
      - checkout
      - docker/install-docker-tools
      # Install Docker client
      - setup_remote_docker:
            docker_layer_caching: true
      # Install Azure CLI
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      # Login to Azure
      - run:
          name: Login to Azure
          command: |
                az login \
                --service-principal \
                --user "6234e69a-81f8-4bbd-bc4f-d58e4e893859" \
                --tenant "15aeef68-4238-42b3-bf77-9d4ffe8b7c5f" \
                --federated-token "${CIRCLE_OIDC_TOKEN}" 

       # Login to Azure Container Registry
      - run:
          name: Login to Azure Container Registry
          command: |
            az acr create --resource-group test --name containerregistrytest1 --sku Basic
               
      - run:
          name: Show current working directory
          command: |
            echo $CIRCLE_WORKING_DIRECTORY
            az acr update -n containerregistrytest1 --admin-enabled true
            az acr login -n containerregistrytest1 --expose-token     
      # Build Docker images
      - run:
          name: Build Docker Images
          command: |
            cd ~/project/AspNetDistributedCaching 
            echo $CIRCLE_WORKING_DIRECTORY
            ls
            docker-compose up -d

      # Push Docker images to Azure Container Registry
      - run:
          name: Push Docker Images to ACR
          command: |
            docker login containerregistrytest1.azurecr.io -u "6234e69a-81f8-4bbd-bc4f-d58e4e893859" -p "KhH8Q~2CwgbR4537~3Ph3y_SC3S--3-aPplGiddg"
            cd ~/project/AspNetDistributedCaching 
            docker ps
            docker images            
            docker tag rediscommander/redis-commander:latest containerregistrytest1.azurecr.io/rediscommander/redis-commander:latest
            docker tag mongo:latest containerregistrytest1.azurecr.io/mongo:latest
            docker tag mongo-express:latest containerregistrytest1.azurecr.io/mongo-express:latest
            docker tag redis:6-alpine containerregistrytest1.azurecr.io/redis:6-alpine
            docker push containerregistrytest1.azurecr.io/rediscommander/redis-commander:latest
            docker push containerregistrytest1.azurecr.io/mongo:latest
            docker push containerregistrytest1.azurecr.io/mongo-express:latest
            docker push containerregistrytest1.azurecr.io/redis:6-alpine
            az container create --resource-group test --registry-username 6234e69a-81f8-4bbd-bc4f-d58e4e893859 --registry-password KhH8Q~2CwgbR4537~3Ph3y_SC3S--3-aPplGiddg --name mycontainer --image containerregistrytest1.azurecr.io/mongo-express:latest --ports 8081
            docker run -p 8081:8081 containerregistrytest1.azurecr.io/mongo-express:latest

workflows:
  version: 2
  build:
    jobs:
      - build