version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Install Docker client
      - run:
          name: Install Docker client
          command: |
            sudo apt update
            sudo apt install -y docker.io

      # Install Azure CLI
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      # Login to Azure Container Registry
      - run:
          name: Azure Container Registry Login
          command: |
                az login \
                --service-principal \
                --user 1ae5290a-5365-436b-bc37-3bfb556cccb3 \
                --tenant 15aeef68-4238-42b3-bf77-9d4ffe8b7c5f \
                --federated-token "${CIRCLE_OIDC_TOKEN}" 

      # Build Docker images
      - run:
          name: Build Docker Images
          command: |
            docker-compose build

      # Push Docker images to Azure Container Registry
      - run:
          name: Push Docker Images to ACR
          command: |
            docker-compose push

workflows:
  version: 2
  build:
    jobs:
      - build